import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MatrixJob } from "./types.js";

export interface GeneratedScenarioArtifacts {
  directory: string;
  sourcePath: string;
  junglePath: string;
  combinedJunglePath: string;
}

function numberValue(record: Record<string, unknown>, key: string): number | null {
  const value = record[key];
  return typeof value === "number" && Number.isFinite(value) ? value : null;
}

function booleanValue(value: unknown): boolean {
  return value === true || value === "low-power";
}

function monkeyString(value: string): string {
  return JSON.stringify(value).replace(/\\u2028|\\u2029/g, " ");
}

function monkeyLiteral(value: unknown): string {
  if (value === null || value === undefined) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "null";
  if (typeof value === "string") return monkeyString(value);
  if (Array.isArray(value)) return `[${value.map(monkeyLiteral).join(", ")}]`;
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>)
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, item]) => {
        if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) {
          throw new Error(`Setting key cannot be represented as a Monkey C symbol: ${key}`);
        }
        return `:${key} => ${monkeyLiteral(item)}`;
      });
    return `{ ${entries.join(", ")} }`;
  }
  throw new Error(`Unsupported scenario value: ${String(value)}`);
}

function forwardSlashes(value: string): string {
  return value.replace(/\\/g, "/");
}

export function renderScenarioSource(job: MatrixJob): string {
  const timestamp = new Date(job.scenario.time);
  if (Number.isNaN(timestamp.valueOf())) throw new Error(`Invalid scenario time: ${job.scenario.time}`);
  const clockMatch = job.scenario.time.match(/T(\d{2}):(\d{2}):(\d{2})/);
  if (!clockMatch) throw new Error(`Scenario time must contain hours, minutes and seconds: ${job.scenario.time}`);
  const hour = Number(clockMatch[1]);
  const minute = Number(clockMatch[2]);
  const second = Number(clockMatch[3]);
  const activity = job.scenario.activity;
  const system = job.scenario.system;
  const weather = job.scenario.weather;
  const lowPower = booleanValue(job.scenario.settings.mode);
  const epochSeconds = Math.floor(timestamp.valueOf() / 1000);

  return `// Generated by CIQ Forge. Do not edit.\n` +
    `using Toybox.Time as Time;\n\n` +
    `module ForgeBootstrap {\n` +
    `    function context() {\n` +
    `        return new CiqForge.RuntimeContext(\n` +
    `            new CiqForge.FixtureClock(\n` +
    `                new Time.Moment(${epochSeconds}),\n` +
    `                new CiqForge.ClockTime(${hour}, ${minute}, ${second})\n` +
    `            ),\n` +
    `            new CiqForge.FixtureSystem(${monkeyLiteral(numberValue(system, "battery"))}, ${monkeyLiteral(numberValue(system, "notifications"))}),\n` +
    `            new CiqForge.FixtureActivity(\n` +
    `                ${monkeyLiteral(numberValue(activity, "steps"))},\n` +
    `                ${monkeyLiteral(numberValue(activity, "stepGoal"))},\n` +
    `                ${monkeyLiteral(numberValue(activity, "bodyBattery"))},\n` +
    `                ${monkeyLiteral(numberValue(activity, "recoveryHours"))},\n` +
    `                ${monkeyLiteral(numberValue(activity, "intensityMinutes"))},\n` +
    `                ${monkeyLiteral(numberValue(activity, "weeklyDistanceMeters"))}\n` +
    `            ),\n` +
    `            new CiqForge.FixtureWeather(${monkeyLiteral(numberValue(weather, "temperatureCelsius"))}, ${monkeyLiteral(weather.condition)}),\n` +
    `            new CiqForge.FixtureSettings(${monkeyLiteral(job.scenario.settings)}),\n` +
    `            new CiqForge.FixtureDisplayMode(${lowPower ? "true" : "false"}),\n` +
    `            new CiqForge.Diagnostics(${monkeyString(job.id)}, true)\n` +
    `        );\n` +
    `    }\n` +
    `}\n`;
}

export async function generateScenarioArtifacts(
  job: MatrixJob,
  jobDirectory: string,
  baseJunglePath: string
): Promise<GeneratedScenarioArtifacts> {
  const directory = path.join(jobDirectory, "generated");
  const sourcePath = path.join(directory, "ForgeBootstrap.mc");
  const junglePath = path.join(directory, "forge-scenario.jungle");
  await mkdir(directory, { recursive: true });
  await writeFile(sourcePath, renderScenarioSource(job), "utf8");
  await writeFile(
    junglePath,
    `base.sourcePath = $(base.sourcePath);"${forwardSlashes(directory)}"\n` +
      `base.excludeAnnotations = $(base.excludeAnnotations);forgeProduction\n`,
    "utf8"
  );
  return {
    directory,
    sourcePath,
    junglePath,
    combinedJunglePath: `${baseJunglePath};${junglePath}`
  };
}
